version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
     - "5000:5000"
    depends_on:
      - redis
    volumes:
      - .:/app
  worker:
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A celery_worker.celery worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    links:
      - redis
  redis:
    image: redis